version: "3.3"
services:

  test-database:
    build: ./database
    image: sample-vault-app-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "test"

  test-api:
    build: .
    image: joatmon08/sample-vault-app
    ports:
      - 8080:8080
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "password"
      DB_ADDRESS: "test-database"
      DB_NAME: "test"
    depends_on:
      - test-database